version: "3.9"

services:
  app:
    build: .
    container_name: authentio_app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:secret@db:5432/authentio_db?sslmode=disable
      - REDIS_ADDR=redis:6379
      - GMAIL_USER=your_gmail@gmail.com
      - GMAIL_PASS=your_app_password
      - JWT_SECRET=supersecretkey
    ports:
      - "8080:8080"
    command: ["./authentio"]

  db:
    image: postgres:16
    container_name: authentio_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authentio_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: authentio_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
